casir_messenger/urls.py
from django.conf.urls import patterns
from django.conf.urls import include
from django.conf.urls import url
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static

urlpatterns = patterns('',
   url(r'^admin/', include(admin.site.urls)),
   url(r'^403/$', TemplateView.as_view(template_name="403.html")),
   url(r'^404/$', TemplateView.as_view(template_name="404.html")),
   url(r'^500/$', TemplateView.as_view(template_name="500.html")),
   url(r'^503/$', TemplateView.as_view(template_name="503.html")),
   url(r'^membre/', include("members.urls", namespace="members")),
   url(r'^dashboard/', include("dashboard.urls")),
   url(r'', include("promotion.urls", namespace="promotion")),

   # Example template
   #url(r'^dashboard/index/$', TemplateView.as_view(template_name="examples/dashboard/index.html")),
   ) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # Add the Debug Toolbar's URLs to the project's URLconf
    import debug_toolbar
    urlpatterns += patterns('', url(r'^__debug__/', include(debug_toolbar.urls)),)

    # In DEBUG mode, serve media files through Django.
    urlpatterns += staticfiles_urlpatterns()
    # Remove leading and trailing slashes so the regex matches.
    media_url = settings.MEDIA_URL.lstrip('/').rstrip('/')
    #urlpatterns += patterns('', url(r'^%s/(?P<path>.*)$' % media_url, 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),)

members/urls.py
from django.conf.urls import url
from django.conf.urls import patterns

urlpatterns = patterns('',
                       url(r'^se-deconnecter/$', 'django.contrib.auth.views.logout', {'next_page': "/"}, name="logout"),
                    )

casir_messenger/templates/503.html
{% extends 'base.html' %}


{% block content %}
<div class="container">
	<div class="row">
		<div class="col-sm-12">
		
		<div class="panel panel-warning">
			  <div class="panel-heading">
			    <h3 class="panel-title">Attention</h3>
			  </div>
			  <div class="panel-body">
			    	Maintenance en cours.
			  </div>
			</div>
		</div>
	</div>
</div>
{% endblock content %}

casir_messenger/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
    <head>
        {% block head %}
            <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
	        <meta name="created" content="{% now "jS M Y h:i" %}" />
	        <meta name="description" content="{% block description %}{% endblock %}" />
	        <meta name="keywords" content="{% block keywords %}{% endblock %}" />
	        <meta name="viewport" content="{% block viewport %}width=device-width, initial-scale=1{% endblock %}" />
		    <meta http-equiv="X-UA-Compatible" content="IE=edge">
		    
            <link rel="icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon" />
            
            <title>{% block title %}Casir messenger &mdash; {% block page_title %}{% endblock page_title %}{% endblock title %}</title>
            
			 <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
			    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
			    <!--[if lt IE 9]>
			      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
			      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		    <![endif]-->
        {% endblock head %}

        {% block mainstyles %}
        	<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        	<link href="{% static 'css/bootstrap-theme.css' %}" rel="stylesheet">
        	<link href="{% static 'css/common.css' %}" rel="stylesheet">
        {% endblock mainstyles %}
        
        {# Additional CSS - specific to certain pages #}
        {% block extrastyles %}{% endblock %}
        
        {% block extrahead %}{% endblock %}
        
        {% block cdn_scripts %}
            <!-- jQuery -->
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        	<script src="{% static 'js/bootstrap.min.js' %}"></script>
        {% endblock %}

        {# Local scripts #}
        {% block scripts %}
        {% endblock %}
        
        {# Additional JS scripts #}
        {% block extrascripts %}{% endblock %}
    </head>
    
    <body id="{% block body_id %}{% endblock body_id %}" class="{% block body_class %}{% endblock body_class %}">
        <div id="wrap">
            {% block header %}
	            <nav class="navbar navbar-default">
			      <div class="container-fluid">
			        <div class="navbar-header">
			          <a class="navbar-brand" href="#">CASIR Messenger</a>
			        </div>
                    {% if user.is_authenticated %}
                        <div class="collapse navbar-collapse pull-right">
                              <ul class="nav navbar-nav">
                                <li class="dropdown">
                                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Connecté en tant que {{ user.username }} <span class="caret"></span></a>
                                  <ul class="dropdown-menu" role="menu">
                                    <li><a href="{%  url "members:logout" %}">Se déconnecter</a></li>
                                  </ul>
                                </li>
                              </ul>
                        </div><!-- /.navbar-collapse -->
                    {% endif %}
			      </div>
			    </nav>
        	{% endblock header %}
        	
        	{% block content %}
        	{% endblock content %}
            
        </div>
        <div class="footer">
            {% block footer %}
            {% endblock footer %}
        </div>
    </body>
</html>